#!/bin/bash

# Build docker image
git clone https://github.com/aycabta/dokku-md-dockerfiles /tmp/dokku-md-dockerfiles
docker build -q=true -t aycabta/mariadb /tmp/dokku-md-dockerfiles
rm -rf /tmp/dokku-md-dockerfiles
